apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streaming-app
data:
  MONGO_DB: "streamingapp"
  MONGO_URI: "mongodb://mongodb:27017/streamingapp"
  CLIENT_URLS: "http://k8s-streamin-streamin-6db1e21b87-1777343515.us-east-1.elb.amazonaws.com"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "streamingapp-vignesh-457660516966"

  AUTH_PORT: "3001"
  STREAMING_PORT: "3002"
  ADMIN_PORT: "3003"
  CHAT_PORT: "3004"
  STREAMING_PUBLIC_URL: "http://k8s-streamin-streamin-6db1e21b87-1777343515.us-east-1.elb.amazonaws.com"