apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.admin }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.images.admin.repository }}:{{ .Values.images.admin.tag }}"
          imagePullPolicy: {{ .Values.images.admin.pullPolicy }}
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: streamingapp-config
            - secretRef:
                name: streamingapp-secret
          livenessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: admin
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.targetPort }}
  type: {{ .Values.service.admin.type }}